name: Daily Screenshot (ForexFactory + Earnings)

on:
  schedule:
    - cron: "0 12 * * *"      # UTC 12:00 → usually EST 7am, EDT 8am
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip unless it's exactly 08:00 America/New_York
        id: check_time
        run: |
          NY_HOUR=$(TZ="America/New_York" date +'%H')
          echo "Hour in New York: $NY_HOUR"
          if [ "$NY_HOUR" != "08" ]; then
            echo "IS_NY_8=false" >> $GITHUB_ENV
          else
            echo "IS_NY_8=true" >> $GITHUB_ENV
          fi

      - name: Abort if not 8am NY
        if: env.IS_NY_8 == 'false'
        run: |
          echo "It's not 8am in New York — skipping build."
          exit 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "playwright" > requirements.txt
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run screenshot script
        run: python screenshot_forexfactory.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

  notify-slack:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Post images to Slack
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"
          REPO="${GITHUB_REPOSITORY##*/}"
          BASE_URL="https://${OWNER}.github.io/${REPO}"

          EARN_URL="${BASE_URL}/pinned_tweet.png"
          FF_URL="${BASE_URL}/forexfactory_full.png"

          cat > payload.json <<'JSON'
          {
            "text": "Earnings and Economic Calendar for the week - For internal use only",
            "attachments": [
              { "title": "Earnings Calendar", "image_url": "__EARN_URL__" },
              { "title": "Economic Calendar (ForexFactory - This Week)", "image_url": "__FF_URL__" }
            ]
          }
          JSON

          sed -i "s|__EARN_URL__|${EARN_URL}|g" payload.json
          sed -i "s|__FF_URL__|${FF_URL}|g" payload.json

          curl -sS -X POST -H 'Content-type: application/json' \
            --data @payload.json \
            "${SLACK_WEBHOOK}"
