name: Weekly Screenshot Bot

on:
  schedule:
    - cron: "0 12 * * 1-5"   # 12:00 UTC = 8:00 AM New York (EST/EDT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install chromium

      - name: Run screenshot script
        run: python screenshot_pinned_tweet.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: site/*.png

  notify-slack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: screenshots
          path: site

      - name: Notify Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -F file=@site/earnings_calendar.png \
               -F "initial_comment=📊 *Earnings Calendar* — For internal use only" \
               -F channels=#general \
               -H "Authorization: Bearer $SLACK_WEBHOOK" \
               https://slack.com/api/files.upload

          curl -F file=@site/forexfactory_high_impact.png \
               -F "initial_comment=💹 *Economic Calendar* — For internal use only" \
               -F channels=#general \
               -H "Authorization: Bearer $SLACK_WEBHOOK" \
               https://slack.com/api/files.upload
