name: Weekly Screenshot Bot (Pages + Slack)

on:
  schedule:
    - cron: '0 12 * * 1'   # Every Monday 12:00 UTC = 8:00 AM America/Toronto
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run screenshot script (outputs to site/)
        run: python screenshot_pinned_tweet.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

notify-slack:
  needs: deploy
  runs-on: ubuntu-latest
  env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  steps:
    - name: Build Slack payload and post
      run: |
        set -euo pipefail

        # Derive public GitHub Pages URLs for the images
        OWNER="${GITHUB_REPOSITORY%%/*}"
        REPO="${GITHUB_REPOSITORY##*/}"
        TWEET_URL="https://${OWNER}.github.io/${REPO}/pinned_tweet.png"
        FF_URL="https://${OWNER}.github.io/${REPO}/forexfactory_usd_cad_high.png"

        # Create JSON payload with placeholders
        cat > payload.json <<'JSON'
        {
          "text": "Earnings and Economic Calendar for the week - For internal use only",
          "attachments": [
            {
              "title": "Pinned Tweet (Earnings)",
              "image_url": "__TWEET_URL__"
            },
            {
              "title": "Economic Calendar (ForexFactory: High impact, USD & CAD)",
              "image_url": "__FF_URL__"
            }
          ]
        }
        JSON

        # Substitute placeholders with actual URLs
        sed -i "s|__TWEET_URL__|${TWEET_URL}|g" payload.json
        sed -i "s|__FF_URL__|${FF_URL}|g" payload.json

        # Post to Slack via Incoming Webhook
        curl -sS -X POST -H 'Content-type: application/json' \
          --data @payload.json \
          "${SLACK_WEBHOOK}"

