name: Weekly Screenshot Bot (Pages + Slack)

on:
  schedule:
    - cron: '0 12 * * 1'   # Every Monday 12:00 UTC = 8:00 AM America/Toronto
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run screenshot script (outputs to site/)
        run: python screenshot_pinned_tweet.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

  notify-slack:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Post images to Slack via webhook (inline)
        run: |
          REPO_FULL="${GITHUB_REPOSITORY}"        # owner/repo
          OWNER="${REPO_FULL%%/*}"                # owner
          REPO="${REPO_FULL##*/}"                 # repo

          TWEET_URL="https://${OWNER}.github.io/${REPO}/pinned_tweet.png"
          FF_URL="https://${OWNER}.github.io/${REPO}/forexfactory_usd_cad_high.png"

          read -r -d '' PAYLOAD << 'JSON'
          {
            "text": "Earnings and Economic Calendar for the week - For internal use only",
            "attachments": [
              {
                "title": "Pinned Tweet (Earnings)",
                "image_url": "REPLACE_TWEET_URL"
              },
              {
                "title": "Economic Calendar (ForexFactory: High impact, USD & CAD)",
                "image_url": "REPLACE_FF_URL"
              }
            ]
          }
          JSON

          PAYLOAD="${PAYLOAD/REPLACE_TWEET_URL/$TWEET_URL}"
          PAYLOAD="${PAYLOAD/REPLACE_FF_URL/$FF_URL}"

          curl -X POST -H 'Content-type: application/json' \
            --data "${PAYLOAD}" \
            "${SLACK_WEBHOOK}"
